version: "3.9"

services:

    web:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www
            - ./build/nginx:/etc/nginx/conf.d
            - ./log/nginx:/var/log/nginx
        networks:
            - public
        links:
            - api
            - mock
            - worker
        depends_on:
            - api
            - mock
            - worker
        env_file:
            - .env
        tty: true

    memcached:
        image: memcached:latest
        container_name: memcached
        ports:
            - "11211:11211"

    api:
        image: resultakak/php:latest
        container_name: api
        restart: always
        volumes:
            - ./src/api:/var/www/api
        working_dir: /var/www/api
        links:
            - db
            - memcached:memcached
            - mock
        networks:
            - public
        env_file:
            - .env
        tty: true

    mock:
        image: resultakak/php:latest
        container_name: mock
        restart: always
        volumes:
            - ./src/mock:/var/www/mock
        working_dir: /var/www/mock
        links:
            - memcached:memcached
        networks:
            - public
        env_file:
            - .env
        tty: true

    worker:
        image: resultakak/php:latest
        container_name: worker
        restart: always
        volumes:
            - ./src/worker:/var/www/worker
        networks:
            - public
        working_dir: /var/www/worker
        links:
            - db
            - redis
            - supervisor
        env_file:
            - .env
        tty: true

    supervisor:
        build:
            dockerfile: Dockerfile
            context: ./build/supervisord/
        container_name: supervisor
        restart: unless-stopped
        volumes:
            - ./src/worker:/var/www/worker
        networks:
            - public
        env_file:
            - .env
        tty: true

    db:
        image: mysql
        container_name: db
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./build/mysql/docker:/docker-entrypoint-initdb.d
            - ./build/mysql/data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - public

    redis:
        image: redis
        container_name: redis
        restart: always
        hostname: redis
        ports:
            - 6379:6379
        networks:
            - public
        tty: true

networks:
    public:
        driver: bridge
